In [20]:
import numpy as np
from numpy import ndarray
from typing import Callable
import math

In [34]:
def deriv(func: Callable[ndarray, [ndarray]], _input: ndarray, delta: float=0.001) -> ndarray:
    return (func(_input + delta) - func(_input - delta))/ (delta * 2)

In [35]:
print(deriv(func=lambda x: x**2, _input=np.array([2,4,4]))) # pow
print(deriv(func=lambda a: 3*a+2, _input=np.array([2,0,4]))) # coeff
print(deriv(func=lambda a: a+2, _input=np.array([2,0,4]))) # const
print(deriv(func=lambda a: np.sqrt(a), _input=np.array([2,1,4]))) # sqrt
print(deriv(func=lambda a: np.log(a), _input=np.array([2,1,4]))) # log

[4. 8. 8.]
[3. 3. 3.]
[1. 1. 1.]
[0.3535534  0.50000006 0.25      ]
[0.50000004 1.00000033 0.25000001]
