In [1]:
import numpy as np
from numpy import ndarray
from typing import Callable, List

## Derivative

In [8]:
# derivative
def deriv(func: Callable[[ndarray], ndarray], _input: ndarray, delta:float=0.001) -> ndarray:
    return (func(_input + delta) - func(_input - delta)) / (delta * 2)
def cube(x: ndarray) -> ndarray:
    return x ** 3
def square(x: ndarray) -> ndarray:
    return x ** 2
def relu(x: ndarray) -> ndarray:
    return np.maximum(0, x)
def sigmoid(x: ndarray)-> ndarray:
    return (1 / (1 + np.exp(-x)))
print(deriv(func=cube, _input=np.array([3,2,0.1])))
print(deriv(func=square, _input=np.array([3,2,0.1])))
print(deriv(func=relu, _input=np.array([3,2,0.1])))
print(deriv(func=sigmoid, _input=np.array([3,2,0.1])))

[27.000001 12.000001  0.030001]
[6.  4.  0.2]
[1. 1. 1.]
[0.04517667 0.10499359 0.24937602]


In [28]:
array_func = Callable[[ndarray], ndarray]
def multiple_inputs_add(x: ndarray, y: ndarray, sig: array_func) -> float:
    # assume both x and y have same shape
    assert x.shape == y.shape
    z = x + y 
    return sig(z)

In [36]:
print(multiple_inputs_add(x=np.array([2,1,4]), y=np.array([4,1,4]), sig=sigmoid))

[0.99752738 0.88079708 0.99966465]


## Derivative 

In [49]:
# for addition
def multiple_inputs_add_backward(x: ndarray, y: ndarray, sig: array_func):
    # forward pass
    a = x + y
    out = sig(a)
    
    # backward pass, 
    # derivative of sig wrt input a
    dsda = deriv(sig, a)
    # derivative of a wrt x and y
    dadx, dady = 1, 1
    dx, dy = dsda * dadx, dsda * dady
    return (out,  (dx, dy))

forward, backward = multiple_inputs_add_backward(x=np.array([2,1,4]), y=np.array([4,1,4]), sig=sigmoid)
print('forward: ', forward)
print('backward: ', backward)

forward:  [0.99752738 0.88079708 0.99966465]
backward:  (array([0.00246651, 0.10499359, 0.00033524]), array([0.00246651, 0.10499359, 0.00033524]))


In [ ]:
# for multiplication
def multiple_inputs_mul_backward(x: ndarray, y: ndarray, sig: array_func):
    # forward pass
    a = x * y
    out = sig(a)
    
    # backward pass, 
    # derivative of sig wrt input a
    dsda = deriv(sig, a)
    # derivative of a wrt x and y
    dadx, dady = y, x
    dx, dy = dsda * dadx, dsda * dady
    return (out,  (dx, dy))

forward, backward = multiple_inputs_mul_backward(x=np.array([2,1,4]), y=np.array([4,1,4]), sig=sigmoid)
print('forward: ', forward)
print('backward: ', backward)

forward:  [0.99966465 0.73105858 0.99999989]


'backward: '

(array([1.34095091e-03, 1.96611927e-01, 4.50140814e-07]),
 array([6.70475453e-04, 1.96611927e-01, 4.50140814e-07]),
 array([3.35237727e-04, 1.96611927e-01, 1.12535203e-07]),
 array([ 8,  1, 16]))