In [1]:
import numpy as np
from numpy import ndarray

In [2]:
# python lists limitations
a = [2,4,4]
b = [3,4,3]
# a * b # error

In [3]:
# with numpy arrays
a = np.array([3,5,6])
b = np.array([3,4,1])
print(a * b)
print(a / b)

[ 9 20  6]
[1.   1.25 6.  ]


In [4]:
# numpy methods
nums = np.array([
    [3,5,7], 
    [4,2,2]])

# sum along x-axis, add rows
print('x', nums.sum(axis=0))

# sum along y-axis, add cols
print('y', nums.sum(axis=1))

x [7 7 9]
y [15  8]


In [5]:
# NumPy ndarrays support adding a 1D array to the last axis

nums1 = np.array([
    [3,5,7], 
    [4,2,2]])
nums2 = np.array([3,6,2])

add = nums1 + nums2
# adds num2 to both rows of num1

print(add)

[[ 6 11  9]
 [ 7  8  4]]


In [6]:
# power
def square(x: ndarray) -> ndarray:
    return np.power(x, 2)
print(square(4))

# leaky_relu
def leaky_relu(x: ndarray) -> ndarray:
    return np.maximum(0.2*x, x)
print(leaky_relu(3))

16
3.0
