In [3]:
import numpy as np
from numpy import ndarray
from typing import Callable
from s_utils import sigmoid, deriv

In [4]:
def matrix_function_forward_sum(X: ndarray, W: ndarray, func:Callable[[ndarray], ndarray]) -> float:
    assert X.shape[1] == W.shape[0]
    # multiply
    N = np.dot(X, W)
    # apply sigmoid function on each element
    S = func(N)
    # sum all elements
    L = np.sum(S)
    return N, S, L

# test
x = np.array([
    [1.0, 2.0, -1.0],
    [0.5, -1.0, 2.0],
    [3.0, 0.0, 1.0]
])   # shape (3,3)

w = np.array([
    [0.2, -0.1],
    [0.5,  0.3],
    [-0.4, 0.7]
])   # shape (3,2)

N, S, L = matrix_function_forward_sum(x, w, sigmoid)
display('matmul:', N)
display('sigmoid:', S)
display('sum:', round(L, 3))


'matmul:'

array([[ 1.6 , -0.2 ],
       [-1.2 ,  1.05],
       [ 0.2 ,  0.4 ]])

'sigmoid:'

array([[0.83201839, 0.450166  ],
       [0.23147522, 0.7407749 ],
       [0.549834  , 0.59868766]])

'sum:'

np.float64(3.403)

In [ ]:
def matrix_function_backward_sum_1(X: ndarray, W: ndarray, func:Callable[[ndarray], ndarray]) -> ndarray:
    assert X.shape[1] == W.shape[0]
    # forward pass
    # multiply
    N = np.dot(X, W)
    # apply sigmoid function on each element
    S = func(N)
    # sum all elements
    L = np.sum(S)
    
    # backward pass
    dLdS = np.ones_like(S)
    dSdN = deriv(func, N)
    dLdN = dLdS * dSdN
    dNdX = np.transpose(W, (1,0))
    # dLdX = np.dot(dSdN, dNdX)
    dLdX = np.dot(dLdN, dNdX)
    
    return L , dLdX

# test
x = np.array([
    [1.0, 2.0, -1.0],
    [0.5, -1.0, 2.0],
    [3.0, 0.0, 1.0]
])   # shape (3,3)

w = np.array([
    [0.2, -0.1],
    [0.5,  0.3],
    [-0.4, 0.7]
])   # shape (3,2)

L , dLdX = matrix_function_backward_sum_1(x, w, sigmoid)
display('forward:', round(L, 3))
display('backward:', dLdX)

'forward:'

np.float64(3.403)

'backward:'

array([[0.0032011 , 0.14413686, 0.11735607],
       [0.01637614, 0.14655545, 0.06326143],
       [0.02547724, 0.19583649, 0.06917589]])

In [20]:
np.random.seed(190204)
X = np.random.randn(3, 3)
W = np.random.randn(3, 2)
display('X:', X)
display('W:', W)
L , dLdX = matrix_function_backward_sum_1(X, W , sigmoid)
display('L', round(L, 4))
display('dLdX', dLdX)

'X:'

array([[-1.57752816, -0.6664228 ,  0.63910406],
       [-0.56152218,  0.73729959, -1.42307821],
       [-1.44348429, -0.39128029,  0.1539322 ]])

'W:'

array([[ 0.75510818,  0.25562492],
       [-0.56109271, -0.97504841],
       [ 0.98098478, -0.95870776]])

'L'

np.float64(2.3755)

'dLdX'

array([[ 0.2488887 , -0.37478057,  0.01121962],
       [ 0.12604152, -0.27807404, -0.13945837],
       [ 0.22992798, -0.36623443, -0.02252592]])